Revert speedup code in calc_sensi.py to avoid dask errors
Removed updates to speed up calc_sensi.py originally introduced in 2d54070d
because they caused the following error with the existing IMI python environment:

```
   Traceback (most recent call last):
     File "/n/holyscratch01/jacob_lab/msulprizio/Test_IMI_globalMerge_noOH/inversion/calc_sensi.py", line 187, in <module>
       calc_sensi(
     File "/n/holyscratch01/jacob_lab/msulprizio/Test_IMI_globalMerge_noOH/inversion/calc_sensi.py", line 123, in calc_sensi
       pert_data = xr.open_dataset(
     File "/n/home05/msulprizio/python/mamba/envs/imi_env/lib/python3.9/site-packages/xarray/backends/api.py", line 575, in open_dataset
       ds = maybe_decode_store(store, chunks)
     File "/n/home05/msulprizio/python/mamba/envs/imi_env/lib/python3.9/site-packages/xarray/backends/api.py", line 485, in maybe_decode_store
       from dask.base import tokenize
   ModuleNotFoundError: No module named 'dask'
````

Signed-off-by: Melissa Sulprizio <mpayer@seas.harvard.edu>